version: '3.9'

services:
  db:
    image: postgres:15
    container_name: univox_postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env

volumes:
  postgres_data: