# Generated by Django 5.2.1 on 2025-07-22 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_topic_post_comment_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='description',
        ),
    ]
